version: '3.7'
services:
  app:
    container_name: nest-rest-api-docker
    restart: unless-stopped
    build:
      context: .
      target: production
    image: nest-rest-api-docker
    working_dir: /home/node/app
    environment: 
      - PORT=5000
      - MONGO_URI=mongodb+srv://admin:wjYuydZXRXzlWsx1@devcluster.ne6re.mongodb.net/devBooks?retryWrites=true&w=majority
    ports: 
      - 5000:5000
    tty: true